### ISSUE TITLE
Does this work with Amazon Music?

### ISSUE THREAD

**Issue by 7UpMan** [chipx86/cloudplaya#12]
I have a number of issues with authentication and the other functions (basically nothing works).

Before I spend a lot of time investigating my configuration, does this still work?  I note that Amazon re-branded to "Amazon Music" from "Amazon Cloud Player" so wondered if they changed the URLs and other other things as part of this and caused these tools to break.

Thanks.

**Comment by micah1701** [comment]
My guess is that it _should_ still work.  I've never set this particular app up because I'm not a python guy but I made my own PHP-based version which I believe uses these same URLs. I built mine 8 months ago and its still working as of today (12/12/2014).  My version is at: https://github.com/micah1701/ACP-API if you want to use it as a reference.

It works fine for accessing and creating your own playlists as well as any files you've purchased or uploaded to your own account.  It can not read or play any of Amazon's free streaming "Prime Music"

**Comment by 7UpMan** [comment]
Thanks for the info.  I may have a look at your version and see if I can get that working.

Right now I have the authentication right (I have checked the session file that is created) but all requests fail.  Every time the code does a `r = requests.post(self.API_URL...` (about line 330 of client.py) it completes (after a warning about HTTPS) with the value `<Response [401]>`, i.e. not the expected response.

I am in the UK so tried changing all the references from amazon.com to amazon.co.uk but that made no difference (the Authentication actually worked with the .com address anyway).

Suggestions welcome.

Thanks.

Ps - have you managed to change the track metadata which is what I would eventually like to do

**Comment by 7UpMan** [comment]
This issue can be closed.  It was driven by the fact that I am a user of amazon.co.uk not amazon.com.  This causes a few issues with the code.  I will create a separate bug report which details the issues and resolutions.

I am a Java guy and this is the first time I have looked at Python so not really up to fixing the raw code but happy to cover the hacks to make it work.
